"""Generate self-contained agent briefs for parallel execution."""

from __future__ import annotations

from pathlib import Path

from orchestrator.lessons import load_golden_packet, recent_lessons
from orchestrator.prd import BRIEFS_DIR, REPO_ROOT, Task, lane_for_phase, load_prd


def build_brief(task: Task) -> str:
    """Create a fresh-context prompt for one agent."""
    prd = load_prd()
    lane = lane_for_phase(task.phase)
    golden = load_golden_packet(task.id)
    golden_section = ""
    if golden:
        golden_section = f"""
## Previous failure (read and avoid repeating)
```json
{__import__('json').dumps(golden, indent=2)}
```
"""

    lessons = recent_lessons(1500)
    acceptance = "\n".join(f"- {c}" for c in task.acceptance_criteria)

    return f"""# Agent brief — {task.id}

**Lane:** {lane} | **Phase:** {task.phase}

## Task
{task.title}

{task.description}

## Acceptance criteria
{acceptance}

## Verification (must pass before complete)
```powershell
python -m orchestrator verify {task.id}
```

Task-only command:
```
{task.verification}
```

## Workflow
1. Implement ONLY this task. No other PRD items.
2. Run `python -m orchestrator verify {task.id}`
3. If pass: `python -m orchestrator complete {task.id}`
4. If fail: `python -m orchestrator fail {task.id} --reason "<stderr summary>"`
5. Never commit `.env` or secrets.

## Project goals
{chr(10).join('- ' + g for g in prd.get('goals', []))}

## Recent lessons
{lessons or '(none yet)'}
{golden_section}
## Stack
python-telegram-bot, FastAPI, SQLAlchemy, pytest, ruff, Hardhat/Adiri testnet.
Repo root: {REPO_ROOT}
"""


def write_brief(task: Task) -> Path:
    """Write brief markdown file for agent."""
    BRIEFS_DIR.mkdir(parents=True, exist_ok=True)
    path = BRIEFS_DIR / f"{task.id}.md"
    path.write_text(build_brief(task), encoding="utf-8")
    return path


def write_next_task_md(task: Task) -> Path:
    """Write tasks/NEXT_TASK.md for session hook injection."""
    from orchestrator.prd import NEXT_TASK_PATH

    content = f"""# NEXT TASK — {task.id}

> Auto-generated by `python -m orchestrator next`. Do not edit manually.

{build_brief(task)}
"""
    NEXT_TASK_PATH.write_text(content, encoding="utf-8")
    return NEXT_TASK_PATH
